### ISSUE TITLE
Define less command

### ISSUE THREAD

**Issue by binguea** [mhinz/vim-grepper#110]
By default there are 8 commands defined

```
:Grepper<TAB>
Grepper   GrepperAg  GrepperGit GrepperPt
GrepperAck  GrepperFindstr GrepperGrep GrepperRg
```

If I define:

`g:grepper.tools=['rg']`

It means I'm using one tool to grep for things. I would like to have only `:Grepper `and `:GrepperRg`
command defined.

I think it makes sense. If one do not have the other back-end tools, vim-grepper does not define the corresponding commands. It's user friendly because it reduces the chances of selecting a tool which does not work.

A small modification will do the job, by adding the `&& index(g:grepper.tools, tool) >=0` check

```
for [cmd, tool] in cmds
  if exists(':'.cmd) != 2 && index(g:grepper.tools, tool) >=0
    execute 'command! -nargs=+ -complete=file' cmd
          \ 'Grepper -noprompt -tool' tool '-query <args>'
  endif
endfor
```

Would you mind this enhancement (if you agree it's an enahcement)?

Thanks,

**Comment by mhinz** [comment]
That needs a `let tools = get(get(g:, 'grepper', {}), 'tools', [])` in case `g:grepper` doesn't exist, but I like the general approach.

Will you send a PR?

**Comment by binguea** [comment]
Even though I think the g:grepper has a default value if not defined by user's customization, I do like your code to get the tools list in a safer way.

After thinking about it, I would like to propose the following:

```
let tools = get(get(g:,'grepper',{}), 'tools',['ack','ag','findstr','git','grep','rg','pt'])
for tool in tools
  let cmd='Grepper'.toupper(tool[0]).tolower(tool[1:])
  if exists(':'.cmd) != 2 
    execute 'command! -nargs=+ -complete=file' cmd
          \ 'Grepper -noprompt -tool' tool '-query <args>'
  endif
endfor
```

The idea is to get the tool names from user's customization. If there is no customization, using a default list.
The advantage is if user has a private tool,  a command is also created, the same way as one of the known tools.

**Comment by binguea** [comment]
Forget to add, I'll send a PR if that sounds good to you...

**Comment by mhinz** [comment]
Hmm.

[Here](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L55-L72) we add all the default values for missing keys from `g:grepper`. (Or all defaults, if `g:grepper` wasn't defined by the user.)

[Here](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L77) we remove all the tools from `g:grepper.tools` that are not installed on the system. Using `executable()` in a loop _can_ (but most of the time doesn't) take a moment on some systems. That's why that code was moved from `plugin/grepper.vim` to `autoload/grepper.vim`. That's how we avoid doing that during Vim's start.

That's why it's not possible to prune the list of default commands at start.

Not sure what's the best way to solve this problem. I agree that it's not elegant to have default commands for tools that are not even installed, though.

**Comment by mhinz** [comment]
@binguea I moved some parts of grepper around and now we simply look at `g:grepper.tools` when defining those commands.
