### ISSUE TITLE
Undefined variable in vimrc g:grepper after recent commit

### ISSUE THREAD

**Issue by nzbart** [mhinz/vim-grepper#120]
I have the following code in my vimrc:

```vim
runtime autoload/grepper.vim
let g:grepper.highlight = 1
let g:grepper.dir = 'repo,file,cwd'
let g:grepper.rg.grepprg .= ' --smart-case'
let g:grepper.tools = ['rg', 'git', 'ag', 'grep', 'findstr']
```

Prior to 118de751ca6771b420aedbceec14c13868fcffda, this worked well, but from that commit onwards, I get the following error when I load Vim:

```
E121: Undefined variable: g:grepper
```

Do I need to modify my vimrc to deal with these changes?

**Comment by mhinz** [comment]
Argh, right. I recently changed the plugin so that only one file has to be sourced.

It should be `runtime plugin/grepper.vim` now. Sorry for the confusion!

**Comment by Konfekt** [comment]
Just curious, what is the point of the `autoload` folder if everything in there can be loaded in the `plugin` folder in one go?

**Comment by mhinz** [comment]
If directory "foo" is part of the `:h 'runtimepath'`, then `foo/plugin/**/*.vim` get sourced when Vim starts. `foo/autoload/**/*.vim` only get sourced when one of their functions is called for the first time.

Thus autoload can be used to avoid work at start. But then I see a lot of plugins that have files in `autoload/` that get used by files from `plugin/`, effectively destroying the purpose of autoload files.

Anyway, grepper is a type of plugin that needs most of it's stuff initialized right away, so splitting it up in two files,  `autoload/grepper.vim` and `plugin/grepper.vim`, didn't make much sense.

The other use of autoload directories is because is for building an API:

```
foo/autoload/foo/api/cursor.vim
foo/autoload/foo/api/status.vim
```

You could run functions from these files from anywhere by doing `:call foo#api#cursor#goto(3, 5)` etc. Everything is properly namespaced. With `foo/plugin/*.vim` would have to use global functions which can obviously clash with other things.

`:h autoload`

**Comment by Konfekt** [comment]
Thank you very much, I learned that @tpope insists on a single file in `plugin` on accounts on a one plugin = one file policy (as in fugitive), but the reasons given for grepper are architecturally to the point.
