### ISSUE TITLE
Strange AdjustWindowHeight Error when performing search

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-grepper#122]
I seem to be getting a strange error when performing a search.

Here's a screenshot of the error. It occurs just before the quickfix window is opened:
![example](https://dl.dropboxusercontent.com/s/gaq7rriawk0x6kn/Developmentdiscorddiscord_app_2017-07-10_16-16-24.png?dl=0)

I am using the latest version of `vim-grepper` and Vim 8.0, with patches 1-692

**Comment by mhinz** [comment]
`s:AdjustWindowHeight()` doesn't come from Grepper, it's another plugin interfering. You can probably find the culprit via `:verb au QuickFixCmdPre,QuickFixCmdPost`.

I'm allowing other plugins to run on `:copen` on purpose. Otherwise plugins like [vim-qf](https://github.com/romainl/vim-qf) wouldn't work.

So, this needs to be fixed in the other plugin.

**Comment by mhinz** [comment]
Since there's nothing I can do about it from Grepper's side, I'm closing this.

Thanks for bringing this up (and feel free to ask further questions if you need help figuring out which plugin is the culprit).

**Comment by amadeus** [comment]
Tracked down the plugin, thanks!
