### ISSUE TITLE
feature request: prepopulate prompt with single quotes

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#136]
Add the possibility `let g:grepper.prompt_quote = 2` that pre-populates the grepper prompt with two single quotes and the cursor in between, for example `grep> '_'`, where `_` = cursor position.

This would allow for more flexibility then `let g:grepper.prompt_quote = 1`.

**Comment by mhinz** [comment]
I usually tend to have a tad less user-friendly but much more flexible options, because otherwise the next person would ask for `g:grepper.prompt_quote = 3` for using double quotes etc. :)

How about a new option `g:grepper.prompt_populate` that can be any string (which includes keys). `g:grepper.<tool>.grepprg` etc. already use `$*` as a placeholder for the query, so you could do what you want like this:

```vim
let g:grepper.prompt_populate = "'$*'\<Left>"
```

What do you think?

**Comment by mhinz** [comment]
Hmm, what else could you populate the prompt with apart from single and double quotes? Maybe `g:grepper.prompt_quote` with `2` and `3` _is_ the better way.

**Comment by Konfekt** [comment]
Well, I prefer your prepopulate option. This way common arguments can be passed to `grep`, such as `-i` = ignorecase. This would be useful for `git grep`, as a compensation for its lack of smart case.

**Comment by Konfekt** [comment]
In this case, a prompt_populate should be definable for any tool.

**Comment by mhinz** [comment]
Hmm, but the `-i` can be added at the prompt on the fly or you just make `-i` a default argument:

```vim
runtime plugin/grepper.vim
" the default is 'git grep -nI'
let g:grepper.git.grepprg += 'i'
```

**Comment by mhinz** [comment]
I decided for extending `g:grepper.prompt_quote` for now. I think that's much easier to explain to users while covering 99.999% of the use cases. :-)

**Comment by Konfekt** [comment]
Ok, thanks! I understand that too much flexibility can end up more confusing than helpful.
