### ISSUE TITLE
Quickfix window splits a single match into a multiline when using sift.

### ISSUE THREAD

**Issue by Puzomor** [mhinz/vim-grepper#147]
There is a problem I'm facing when using vim-grepper with sift.
I'm using Windows 10 x64, sift v0.9.0 and Neovim v0.2.3.
When I use the command prompt to search for let's say "a_string", everything works, so I'm assuming the problem isn't with sift.
I use vim-grepper set up like this:
```
let g:grepper = {
  \ 'tools': ['sift'],
  \ 'sift' : {
  \   'grepprg': 'sift --err-skip-line-length --type=cpp --line-number -e $* Sources',
  \   'grepformat': "%f:%l:%m",
  \   'escape': '\+*^$()[]',
  \ },
  \ 'dir': 'pwd'}
```
The problem is that sometimes, the results are weirdly split up in the quickfix window.
Let's say files a.cpp, b.cpp and c.cpp all contain "a_string" in lines 9.
the expected output in quickfix window is
```
Sources\a.cpp|9| a_string
Sources\b.cpp|9| a_string
Sources\c.cpp|9| a_string
```
but sometimes one (or more) of the results end up split, like this
```
|| Sources\a.cpp:
|| 9:a_string^M
Sources\c.cpp|9| a_string
Sources\b.cpp|9| a_string
```
and I can't use them as a normal quickfix entry.
The only way to "fix" this is to re-run the search and hope none of my results end up split (which is nearly impossible on 50+ search results).
What can I do to further investigate this weird issue?
Does anyone else have any similar issues?

**Comment by mhinz** [comment]
Neovim (which is based on [libuv](https://github.com/libuv/libuv)) gets the sift output in chunks. This can be only part of a line of several lines at once.

That's why we have to do [this stunt](https://github.com/mhinz/vim-grepper/blob/bb66c6623fbeff1b141fe4d385d4be7ff9f009d1/plugin/grepper.vim#L151-L166) to split it up into complete lines. But this code _should_ be correct. (I never had splitted lines in the quickfix window so far, but I'm not working on Windows either.)

We recently enabled buffering.. could you see if it makes any difference if you remove these two lines? -> https://github.com/mhinz/vim-grepper/blob/bb66c6623fbeff1b141fe4d385d4be7ff9f009d1/plugin/grepper.vim#L762-L763

**Comment by Puzomor** [comment]
Still the same.

**Comment by mhinz** [comment]
Okay, please apply this diff:

```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index 7e1529b..bb14f9e 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -147,6 +147,7 @@ function! s:on_stdout_nvim(_job_id, data, _event) dict abort

   let orig_dir = s:chdir_push(self.work_dir)

+  echomsg 'RAW: '. string(a:data)
   try
     if empty(a:data[-1])
       " Second-last item is the last complete line in a:data.
@@ -164,6 +165,7 @@ function! s:on_stdout_nvim(_job_id, data, _event) dict abort
               \ + a:data[1:]
       endif
     endif
+    echomsg 'BUF: '. string(self.stdoutbuf)
     if self.flags.stop > 0
       let nmatches = len(self.flags.quickfix ? getqflist() : getloclist(0))
       if nmatches >= self.flags.stop || len(self.stdoutbuf) > self.flags.stop
```

Then, if you get the issue again, check `:messages`.

**Comment by mhinz** [comment]
Just to be sure: It works now on master or with the patch applied?

**Comment by Puzomor** [comment]
Works without any patches applied, although I kept the `echomsg`s if the problem occurs ever again.

**Comment by mhinz** [comment]
Since it didn't seem to happen again so far, I'm closing this. Please feel free to reopen in any other case.
