### ISSUE TITLE
Perform search as per vim's path variable

### ISSUE THREAD

**Issue by SiliconKite** [mhinz/vim-grepper#168]
I usually work in multi location projects, where source files are distributed among different servers, databases, etc. What I isually do is to add these locations to vim's path, so, for instance, I can 'gf' into these files. 
When firing a search to find a string, is it possible to somehow specify that the search is to be performed not at the current location but at all the levels specified by path ?
Thanks

**Comment by mhinz** [comment]
Unfortunately this plugin is not very well suited for such a use case. It's not as easy as simply putting multiple directories on the command line, since a few VCS tools require changing to directories etc. 

Something like `:Grepper -dir vimpath` would be cool, but it's hard to make it work with all potential VCS tools.

But.. if your intention is to simply get the job done, tell me your VCS, and I'll come up with a little glue code that you could put in your vimrc!

**Comment by SiliconKite** [comment]
Thanks mhinz for the reply. I ended up adding the folders to the path variable, I can live with that
