### ISSUE TITLE
vim-grepper greps in current work dir of different tab

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#192]
Perhaps since the fix to https://github.com/mhinz/vim-grepper/issues/189 , after opening Vim the following steps

1. Opening a file in a git repository
2. Setting the current work dir to the root of this git repository
3. Opening a new tab
4. Opening a file in a different git repository
5. Setting the current work dir to the root of this (different) git repository
6. Switching back to the first tab
7. Vim-greppering for a word

result in: only results of the git repository of the SECOND tab appear.

Expected: only results of the git repository of the FIRST tab appear.

**Comment by mhinz** [comment]
Do you use `:cd` to switch the _global_ directory? Then that behaviour is to be expected, since Grepper uses the current working directory by default.

- Use `:Grepper -dir repo,file`.
- Use `:Grepper` and then hit `<c-d>` to switch the `-dir` option on the fly.
- Use `:lcd` (window-local) or `:tcd` (tab-local) to switch the directory in the second tab.

**Comment by Konfekt** [comment]
I am using, after installing `vim-fugitive`,
```
    autocmd BufRead,BufNewFile,BufFilePost *
            \ if !exists('g:SessionLoad') && exists(':Glcd') && isdirectory(expand('%:p:h')) |
            \   Glcd |
            \ endif
```
where `Glcd` indicates the use of `:lcd`.

**Comment by Konfekt** [comment]
Together with this autocmd I am using `let g:grepper.dir = 'filecwd'`;  it used to work fine before.

**Comment by Konfekt** [comment]
When setting, as you proposed, `let g:grepper.dir = 'repo,filecwd'` the issue vanishes.

**Comment by mhinz** [comment]
I couldn't reproduce that so far.

When you're back in tab 1, what's `:pwd` before `:Grepper` returns wrong results?

**Comment by Konfekt** [comment]
I am sorry my fault, to reproduce it you have to vim-grepper in the second tab, then switch to the first and vim-grepper in it; it will show the same results as in the first tab, despite its :pwd being different and `grepper.dir = filecwd` set.

Therefore the order is

 1. Opening a file in a git repository
2. Setting the current work dir to the root of this git repository
3. Opening a new tab
4. Opening a file in a different git repository
5. Setting the current work dir to the root of this (different) git repository
7. Vim-greppering for a word
8. Switching back to the first tab
9. Vim-greppering for a word

which results in the same results as in the second tab being shown, despite `grepper.dir=filecwd` being set.

**Comment by mhinz** [comment]
Okay, let's take a specific example. You may need to alter the paths, but let's use the fugitive repo for tab 1 and vim-grepper for tab 2:

```vim
" test.vim

edit ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
lcd ~/.vim/bundle/vim-fugitive/plugin

tabedit ~/.vim/bundle/vim-grepper/plugin/grepper.vim
lcd ~/.vim/bundle/vim-grepper/plugin

let g:grepper.dir = 'filecwd'

Grepper -tool git -noprompt -query file
" :Grepper is async. Give it a moment to collect matches and open qf window.
sleep 500m

tabprevious
Grepper -tool git -noprompt -query file
```

```
$ vim -S test.vim
```

Using this, I end up in tab 1, with the qf window showing `fugitive.vim` for the first matches. When I use `gt` to switch to the other tab, the path within the qf window stays relative (which is wrong, because `:pwd` is `/Users/mhi/.vim/bundle/vim-grepper/plugin`, but opening an entry still uses the absolute path and opens the right file. Nevertheless, it's a displaying bug).

But apart from that bug, everything seems to work as expected.

It also works if I remove both `lcd` lines, because of the `g:grepper.dir = 'filecwd'`. It's probably easier to see when adding `-noqf` to the `:Grepper` flags. Then the location list is used and both tabs show different matches opposed to the global quickfix window.

Did I miss something?

**Comment by Konfekt** [comment]
Okay, I can confirm that it is the autocmd
```vim
augroup epnFugitiveProjectRoot
    autocmd!
    autocmd BufRead,BufNewFile,BufFilePost *
            \ if !exists('g:SessionLoad') && exists(':Glcd') && isdirectory(expand('%:p:h')) |
            \   Glcd |
            \ endif
augroup END
silent doautocmd epnFugitiveProjectRoot BufReadPre,BufNewFile,BufFilePost
```
that causes the issue. For some reason, it will make grepper always switch back to the work dir where grepper was first invoked. 

For some reason the `lcd` of the quickfix list remains that of this work dir.

**Comment by mhinz** [comment]
Why do you think it's Grepper that switches to the wrong directory?

I tried this:

```vim
autocmd!
autocmd BufRead,BufNewFile,BufFilePost *
      \ if !exists('g:SessionLoad') && exists(':Glcd') && isdirectory(expand('%:p:h')) |
      \   echom 'Before: '. getcwd() | Glcd | echom ' After: '. getcwd() |
      \ endif
```

And got:

```vim
" second tab
Before: /Users/mhi/.vim/bundle/vim-grepper/plugin
 After: /Users/mhi/.vim/bundle/vim-grepper
" first tab
Before: /Users/mhi/.vim/bundle/vim-fugitive/plugin
 After: /Users/mhi/.vim/bundle/vim-grepper
" first tab (qf window)
Before: /Users/mhi/.vim/bundle/vim-fugitive/plugin
 After: /Users/mhi/.vim/bundle/vim-grepper
```

So it seems that `:Glcd` switches to the wrong directory.

**Comment by Konfekt** [comment]
Thank you, sorry for the noise unrelated to vim-grepper. 

The autocmd should check if `isdirectory(expand('%:p:h'))` makes sense after all, in the quickfix window it does not, by an additional check:
```vim
    autocmd BufRead,BufNewFile,BufFilePost *
            \ if !exists('g:SessionLoad') && exists(':Glcd') && empty(&l:buftype) && isdirectory(expand('%:p:h')) |
            \   Glcd |
            \ endif
```
solves the issue.

**Comment by mhinz** [comment]
Hmmmm, I'm not really sure how that solves the issue, but solved is solved, I guess. :-)

**Comment by Konfekt** [comment]
Yeah, it solves it in the sense that the `bftype` of `quickfix` window is nonempty, and there is no meaningful repo dir of a buffer that does not belong to a file, in particular, whose `bftype` is nonempty.
