### ISSUE TITLE
--noopen option is not working if rg -A/B/C is set

### ISSUE THREAD

**Issue by at2021** [mhinz/vim-grepper#197]
In .vimrc, I set 

> let g:grepper.rg.grepprg = 'rg -H --no-heading --vimgrep -A3'
let g:grepper.open = 0
autocmd User Grepper nested vertical copen

I want to change the default copen command. but grepper would open the quickfix window in the bottom anyway.

I belive it is because the code in plugin/grepper.vim, line 954.

>   " Also open if the list contains any invalid entry.
  if a:flags.open || !empty(filter(list, 'v:val.valid == 0'))
    execute (qf ? 'botright copen' : 'lopen') (size > 10 ? 10 : size)
    let w:quickfix_title = cmdline
    setlocal nowrap

**Comment by mhinz** [comment]
Yes, it probably happens because the output of `rg` doesn't match the [expected output format](https://github.com/mhinz/vim-grepper/blob/9348496c9fe017e5f8f89a71a2772704e3720415/plugin/grepper.vim#L46) defined by `g:grepper.rg.grepformat` and thus the quickfix list has invalid entries (lines starting with `||`).

Try this:

```vim
let g:grepper.rg.grepformat = '%f:%l:%c:%m,%-G--,%+G%.%#'
```

This marks all lines after a valid `%f%l%c:%m` entry as general information entries (and therefore valid entries) and also removes the unneeded `--` lines.

See `:h errorformat` for the whole truth.

**Comment by mhinz** [comment]
Another solution, without setting `g:grepper.rg.grepformat`, would be to move the quickfix window after opening:

```vim
let g:grepper.open = 1
let g:grepper.switch = 1
autocmd User Grepper nested wincmd L
```

**Comment by at2021** [comment]
Thank you, and the solution work find.
