### ISSUE TITLE
Feature request: bang for fast query

### ISSUE THREAD

**Issue by mg979** [mhinz/vim-grepper#210]
Without changing default options, to skip the prompt and provide a pattern I have to do (unless I'm mistaken?):
```
:Grepper -noprompt -query "pattern"
```

With a bang it could be:
```
:Grepper! pattern
```

So that everything is treated as a quoted pattern, it would imply -noprompt and -query, and no other options would be allowed (default options would be applied).

**Edit**: now that I think about it, this also works:
```
command! -nargs=1 Vimgrep Grepper -noprompt -query <q-args>
```

**Comment by mhinz** [comment]
Yup, I suggest using an alias command like that.

Otherwise I would have to change our [custom argument parser](https://github.com/mhinz/vim-grepper/blob/a73a9dc920bd0b3ba8b298c258bd4d4814d9a162/plugin/grepper.vim#L543-L616) just for this shortcut. Not really worth it given that it's highly subjective. :)
