### ISSUE TITLE
arrow keys in terminal Vim

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#221]
As discussed in https://github.com/mhinz/vim-grepper/pull/106 and https://github.com/mhinz/vim-grepper/pull/89 remapping `esc` to cancel the search has the same effect on the arrow keys.

I am wondering if these fixes have been silently moved out of the code base? Arrow keys in Vim only work for me when removing
```vim
" plugin/grepper.vim (line 770)
cnoremap <silent> <esc> <c-\>e<sid>set_prompt_op('cancelled')<cr><c-c>
```

If so, could this mapping be made optional? As a compromise `<esc><esc>` would also cause no problem.

**Comment by mhinz** [comment]
Argh, another Vim-only issue. I tend to miss these issues because Nvim has slightly saner key input handling due to its [libtermkey](http://www.leonerd.org.uk/code/libtermkey) dependency.

And even in Vim I wouldn't have recognized it, because I usually use this for going up/down:

```vim
cnoremap <c-n>  <down>
cnoremap <c-p>  <up>
```

Anyway, I can reproduce it. The fix from back then doesn't work, because we don't use magic strings anymore.

I'll try to come up with something!

**Comment by Konfekt** [comment]
Not sure what the Vim way is to move the cursor sideways on the Vim command line, but it hit me every time I tried to do so by using the left or right cursor keys.

**Comment by mhinz** [comment]
Please try the latest version. It should work again!

**Comment by Konfekt** [comment]
Thank you! This makes using vim-grepper even more convenient.
