### ISSUE TITLE
Search only in current buffer?

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-grepper#27]
Is there a way to achieve this? Sorry if it is obvious and I've overlooked something. I didn't find anything in the docs.

**Comment by mhinz** [comment]
Depends on the tool, so you have to set grepprg`. Mind that `%` in the command-line will be replaced with the current value.

E.g. a git grep can be limited to a certain file by: `git grep query path/file.ext`. So you can use `%` to get the file, and since the query doesn't come last, we have to use grepper's placeholder `$*`, e.g.

```viml
nnoremap <leader>g :Grepper -grepprg git grep -nI $* %<cr>
```

**Comment by nhooyr** [comment]
ok thanks

**Comment by nhooyr** [comment]
@mhinz how would I do it if I wanted it to be a command instead of a mapping?

**Comment by mhinz** [comment]
It's exactly the same then:

```viml
nnoremap <c-g> :Grepper -grepprg git grep -nI $* %<cr>
```

**Comment by nhooyr** [comment]
@mhinz that a mapping still?

**Comment by nhooyr** [comment]
I tried 

```vim
command! Cag Grepper -grepprg ag --vimgrep $* %<cr>
```
but it always returns 'ERR: Error opening directory filename^M: No such file or directory'

**Comment by nhooyr** [comment]
Never mind I'm retarded thanks.

Just one last question though. Do you think its worth adding in a way to search a vim buffer without writing it to a file?

**Comment by nhooyr** [comment]
Is that not a mapping? So I tried

```vim
command! -nargs=* Cag Grepper -grepprg ag --vimgrep <args> %<cr>
```
But it still asks for the pattern like the mapping does.

Also do you think its worth adding a mode in which instead of sending the filename to the tool, you literally write the buffer to its stdin so that it doesn't have to be a file on the disk?

**Comment by nhooyr** [comment]
I got it working like this

```vim
command! -nargs=* Cag Grepper -tool ag -grepprg ag --vimgrep -G %
```

Now the only problem is being able to send the query as well instead of it asking after.

**Comment by mhinz** [comment]
Oh, I misread what you wrote and thought you wanted a mapping.

Anyway, your approach so far is correct, see `:h :Grepper`. But now ou're hitting a technical issue, since you want to mix the `-grepprg` and `-query` flags. Unfortunately this doesn't work at the moment, because both flags have be the last ones. This is because the parser never knows when the input for the flag ends and simply using quote isn't working as expected.

**Comment by nhooyr** [comment]
Alright well thanks anyways. I'll just use the mapping for now.

**Comment by nhooyr** [comment]
Oh wait what do you think about adding a option in which instead of sending the filename to the tool, you literally write the buffer to its stdin so that it doesn't have to be a file on the disk?

**Comment by mhinz** [comment]
Obviously this wouldn't work for tools like `git grep`, but the idea is pretty interesting. Let me play around with `ag` a bit.

**Comment by mhinz** [comment]
Back to the prior question: I guess I need another coffee. Simply skipping the prompt should be easy to implement. E.g. a `-noprompt` flag.

**Comment by mhinz** [comment]
Okay, so I settled on these things to do in the next days:

1. Implement `-noprompt`. Should make it possible to create commands like `command! -nargs=* Grepper -noprompt -tool ag -grepprg ag --vimgrep <args> %`.

1. Remove `-query`. This was introduced for the sole purpose of creating commands and is superceded by point 1.

1. Searching in all opened buffers. I might just add another placeholder to `-grepprg`, e.g. `$+` or so, that gets replaced by all opened files.

**Comment by nhooyr** [comment]
Sounds good!

**Comment by mhinz** [comment]
Implemented `-noprompt`. `command! -nargs=* Grepper -noprompt -tool ag -grepprg ag --vimgrep <args> %` should work now.

I also added `$.` as a placeholder to `-grepprg`, so you can do the same from a mapping, too. Try `:Grepper -grepprg ag --vimgrep $* $.`.

Moreover, I added the `$+` placeholder, which will be replaced by all opened files: `:Grepper -grepprg ag --vimgrep $* $+`.

**Comment by nhooyr** [comment]
sweet. thanks!

**Comment by mhinz** [comment]
I think this can be closed then.

Thanks for the feedback and good luck with your exams!

**Comment by mellery451** [comment]
sorry to pile on this old thread, but I would like just the simple mapping to search in current file and I've tried:

`nnoremap <leader>sf  :Grepper -tool ag -cword -noprompt $* %<cr>
`

...which doesn't produce errors when invoked, but tells me "no matches" which of course is nonsense because the current word is by definition in the current file (the buffer is saved). How can I debug what's going wrong here?

**Comment by reportaman** [comment]
@mhinz Is it possible (with any external grep program) to search unsaved contents in a v buffer? The use case I am thinking is of a large (in GBs) file that would take just too much time to write to disk, and internal grep in vim isn’t that fast (compared to ripgrep or the likes).
