### ISSUE TITLE
Fallback option to try next tool in list

### ISSUE THREAD

**Issue by Mattias-** [mhinz/vim-grepper#35]
It would be sweet with a feature that fall back to the next tool in the tools list when the first one fails or have no matches.

My use case is that I prefer to use `git grep` over `ag` but when not in a git dir I want `ag` to do the searching since `git grep` fails and `ag` is the next tool in my tools list.

**Comment by mhinz** [comment]
A fallback on no found matches is a bit extreme. :) But I see the problem.

Since I don't know what other tools people add on their own, I'd prefer a general solution. An option, e.g. `g:grepper.fallback = 1`, that simply retries the second tool in `g:grepper.tools` if the the primary tool returns something != 0 would be both simple to implement and easy to grasp.

Unfortunately I'm a busy today since I plan a trip for this week, so this won't happen before Saturday. But it will happen.

Thanks for the proposal!

**Comment by mhinz** [comment]
Sorry, but this feature won't happen. The main problem is that by only inspecting the return value, there's no way to distinguish between `an error happened` and `nothing found`.

The total hacky and fragile way would be to parse the output for certain text that can happen to be different for different shells.. typical rabit hole programming. It would also add quite a lot of grep tool-specific code.

Putting it in a nutshell, I'd like to keep the code simple.

**Comment by manasthakur** [comment]
Can't this be done by just checking whether the current directory is in a git repository? For example:
```
let tmp = system("git rev-parse --is-inside-work-tree")
let is_git_repo = v:shell_error == 0
```

**Comment by mhinz** [comment]
@manasthakur 

The "problem" is that I want to keep the plugin as general as possible. Thus I'd like to avoid tool-specific code.

But.. due to popular demand, I might add an autoload function that somehow reuses the recently added `b:grepper` to dynamically add/remove `'git'` to/from the tool list.

Then something like this could be used:

```vim
autocmd BufAdd * call grepper#check_for_git()
```
