### ISSUE TITLE
Provide completion of options for :Grepper

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#41]
A custom completion for `:Grepper` with the available options would be nice to have.

**Comment by mhinz** [comment]
Well, I'd like to keep the built-in file completion, because I couldn't rebuild the same functionality with a custom completion. I tried to do that for the prompt, but that's the best I could come up with: https://github.com/mhinz/vim-grepper/blob/192ea5ae2d2888562e9a27c9bba972eafb972881/autoload/grepper.vim#L106-L118

_If_ it would be possible to implement `-complete=file` with a custom completion, adding completion for flags would be the tiniest problem. :)

**Comment by mhinz** [comment]
Should be working now.

Note: I left out the `-qf`/`-noqf` alias on purpose.

**Comment by blueyed** [comment]
Awesome, thanks!
Tested it only briefly, and noticed that e.g. `-tool` could complete from the list of tools, but it's very nice already! :)

**Comment by mhinz** [comment]
No problem!
