### ISSUE TITLE
Do jump after open

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#47]
With both `jump` and `open` I've found that jumping should be done after opening, otherwise I've ended up in the quickfix list.

That might be related to (i.e. caused by) https://github.com/mhinz/vim-grepper/pull/44?!

**Comment by mhinz** [comment]
Well, either one or the other has to take priority and it happened that I checked for `-jump` first. :-)

IIRC, the logic was also easier this way, because otherwise the code for `-switch` has to take `-open` _and_ `-jump` into account, so there was more `<c-w>p` action.

So, either `:Grepper -jump -open -noswitch` or `let g:grepper = { 'switch': 0 }`.
