### ISSUE TITLE
Add support for :vimgrep

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-grepper#5]
`:vimgrep` is actually the only grep I need async for. What do you think?

**Comment by mhinz** [comment]
I assume you want to use Vim regular expressions in this case, but since there's no external tool for this, I wouldn't know how to make it async.

**Comment by justinmk** [comment]
External tool is nvim!

**Comment by mhinz** [comment]
Hah, I'll look into it.

**Comment by mhinz** [comment]
I just decided that this feature doesn't really fit into this plugin, since it wouldn't be possible to implement for Vim as well.

But it's interesting anyway and might be worth a small plugin on its own.

**Comment by bimlas** [comment]
Did your opinion changed since Vim has builtin async support?

**Comment by mhinz** [comment]
I really wonder why people would prefer using slow `:vimgrep` over dedicated tools? :-) Just for using Vim regular expressions?

If I'm going to implement it, it would require every user to put a shell script in their `$PATH` (`vimgrep` and `nvimgrep` probably), which `[n]vim +'vimgrep ...' +...` and writes the results to a temporary file which gets cat'd afterwards.

It must act like a normal Unix tool that just prints to stdout, so it can easily get added to Grepper, because I certainly won't add any `:vimgrep`-specific code to the plugin.

Is it worth it? What are you opinions, @bimlas and @justinmk?

**Comment by justinmk** [comment]
> why people would prefer using slow :vimgrep over dedicated tools? :-) Just for using Vim regular expressions?

Yes, and it respects 'wildignore' and other use settings. 

> If I'm going to implement it, it would require every user to put a shell script in their $PATH (vimgrep and nvimgrep probably), which [n]vim +'vimgrep ...' +... and writes the results to a temporary file which gets cat'd afterwards.

Oh, I would skip it then. 

> It must act like a normal Unix tool that just prints to stdout, so it can easily get added to Grepper, 

Then let's make `nvim` act like a standard unix tool. This can be approximated by [contortions like this](https://github.com/neovim/neovim/blob/master/scripts/vim-patch.sh#L134-L136) but it should be easier and there should be better support for sharing state between child `nvim` instances.

**Comment by mhinz** [comment]
> Yes, and it respects 'wildignore' and other user settings.

Good point.

> Oh, I would skip it then.

What I thought. ;-)

> Then let's make nvim act like a standard unix tool. This can be approximated by contortions like this but it should be easier and there should be better support for sharing state between child nvim instances.

Sounds like an exciting feature for Neovim 3.0, but that's still a few milestones ago, heh.

Putting it in a nutshell, to make it work for Neovim _and_ Vim, and without destroying the beauty of the plugin, a shell (or batch) script will be required.

I'll look into coming up with a solution and making it more convenient by shipping it with the plugin.

**Comment by bimlas** [comment]
* Generate the `vimgrep` command (as used inside Vim, like `noautocmd vimgrep /regex/ files...`) and store it in a variable (like `vimgrep_cmd`)
* Generate a temporary filename and store it in a variable (like `vimgrep_tmp`)
* Execute (N)Vim as a job with the variables passed through the "command line" (like `vim +'content_of_vimgrep_cmd | copen | write content_of_vimgrep_tmp'
* The `vimgrep_tmp` will contain the matches like these

```
linux\home\bin\lsdep.sh|36 col 5| print $0;                          \
linux\home\bin\packlist.sh|5 col 11| apt-get --print-uris --yes install $* | sed -n "
linux\home\bin\sysinfo.sh|2 col 13| # sysinfo - print hardware information summary
```

I don't know if this is a possible usage of jobs (never used it) but it doesn't needs to use `vimgrep` as a script.

**Comment by mhinz** [comment]
> I don't know if this is a possible usage of jobs

Unfortunately it's not. ;-) You can't execute VimL (functions or commands) asynchronously.

The whole point of wrapping vimgrep in an external script, is because there's no other way to call `:vimgrep` asynchronously.

That said, I see no technical reason why this approach shouldn't work. The user shouldn't notice what happens in the background. I just need the time to hack it up in the next days.

**Comment by justinmk** [comment]
`:vimgrep` can be run as a job by invoking it in a child instance. The results can either be written to a file or dumped to stdout (probably a bit awkward).

**Comment by mhinz** [comment]
Yea, that's the plan. When I said "shell script", I meant "child instance", of course. ;-) The approach stays the same: `:vimgrep`, processing the output of `getqflist()`, write to a temporary file in a way that's easy to digest via `grepformat`.

**Comment by mhinz** [comment]
Okay, but the approach is basically the same. Getting the results is not the real problem. The problem is fitting it into the current code. At least for the operator, I see a few problems..

But yea, let's just start with a new branch and see where it's going.

**Comment by mhinz** [comment]
After some playing around, I decided against this feature (again).

It just doesn't fit in compared to all the other tools, since it needs too much `:vimgrep`-specific code. IMHO, it should be a plugin on its own. `vim-async-vimgrep`, anyone?

Here's the working code for Neovim:

https://gist.github.com/mhinz/1d62b803d328f83551e15c97a4b57868

Adding Vim support by using `job_start()` shouldn't be hard.

**Comment by mhinz** [comment]
In case you're interested in a little hack:

```vim
let g:grepper = {
      \ 'tools': ['git', 'ag', 'vimgrep'],
      \ 'vimgrep': {
      \   'grepprg':    "vim -es +'vimgrep /$*/ ** | cw | %p | qa'",
      \   'grepprgbuf': "vim -es +'vimgrep /$*/ $. | cw | %p | qa'",
      \   'grepformat': '%f|%l col %c|%m' }}
```

This makes everything work but the operator. Try this:

```
:Grepper -tool vimgrep
:Grepper -tool vimgrep -query foo
:Grepper -tool vimgrep -buffers -query foo
```

**NOTE**: Neovim doesn't handle the `-es` approach, thus Neovim users will have to create a vim subprocess as well. This could be confusing, if `~/.vim/vimrc` is not symlinked to `~/.config/nvim/init.vim` and defines other values for `'suffixes'`, `'wildignore'` etc.

**Comment by justinmk** [comment]
Why wouldn't `-es` work with Nvim?

**Comment by mhinz** [comment]
Well, the `-es` probably does, but no output will be written to stdout.
