### ISSUE TITLE
Exact match highlighting

### ISSUE THREAD

**Issue by purpleP** [mhinz/vim-grepper#60]
Imagine I have two files. One of them opened in current window.

```
1.txt
foo

2.txt
foo
```

Then I'm searching something with Ag command.
I'd like that `foo` in buffer that contains 1.txt would be highlighted after search is ended. And when switching to next quickfix item which would be 2.txt `foo` also be immediately highlighted.

I've thought and asked about it and I think that this is doable. You need only two things
- Get line of the match with start column and end column.
- Create matchgroup (if it's not already there) to highlight search matches.
- Call addmatchpos when results are available and in switching quickfix items

The first can be done in two ways I think. One is you can make search program output line, column of the match start and match only. This way you would know end column by adding match length to column.
Second is search for color codes in lines and because this color codes would wrap the match you can extract match itself.

**Comment by purpleP** [comment]
Oh, and in case you're wondering why not just add what user searched for to the `/` register - because this wouldn't work with regex searches.

**Comment by mhinz** [comment]
Do you know that there's simple highlighting support already? It's enabled by `:Grepper`s `-highlight` flag. (See `:h :Grepper`.) 

Simple because it indeed uses the `/` register, although it should handle simple cases of `.*` and a few other patterns just fine. It's a "good enough" approach that doesn't rely on external tools.

Put this in your vimrc to turn on highlighting for `:Ag`:

```vim
command! -nargs=* -complete=file Ag Grepper -noprompt -highlight -tool ag -query <args>
```

As for the other suggestions:

- **Way 1**: But how do you "search" the output line to get even the starting column when using regexp? To get an exact answer, you'd have to use the same tool again. And then you have the same problem again: no ending column. (Some tools don't even report the starting column.)
- ** Way 2**: No, just no. :-) Parsing ANSI escape sequences only leads into a deep, deep rabbit hole. Some tools might not even provide coloured output.

**Comment by purpleP** [comment]
@mhinz First of all I've tried enable highlight via `g:grepper`, but it didn't work out for some reason.

About the first way. Ag can report starting column. You don't need to search for it youself. Then, as I've said - you can make Ag output match only and from that you can get the length of match. Start column + length = end column. And there it is - you arguments for the matchpos ready.
Unfortunately I know only basics of vimscript, so most of you code is mumbo jumbo to me, so I can't add this myself in any reasonable time, but this shouldn't be hard to do, right?

What's harder to do is display the whole line in quick fix with this approach. I don't really need that myself, but other people probably would prefer this. This is also achievable. We can just take line numbers from ag output and get this lines manually from all files with matches.

I sense that you will say something like "this is too much work", "no one really needs this", so would you at least accept pull request with this feature sometime?

And I don't like things that's "good enough" when there's clearly a way to make them better. Never settle on the mediocracy.

**Comment by mhinz** [comment]
> First of all I've tried enable highlight via g:grepper, but it didn't work out for some reason.

What was the exact line? A quick test with `let g:grepper = { 'highlight': 1 }` and searching for "foo" afterwards worked just fine.

> And I don't like things that's "good enough" when there's clearly a way to make them better. Never settle on the mediocracy.

Well, this misses the point. The approach wasn't chosen because it's easier to implement, but because it works the same for all supported tools and tools added by the user.

> Ag can report starting column. You don't need to search for it youself. Then, as I've said - you can make Ag output match only and from that you can get the length of match.

And as I've said, that might not work for other tools, which is my main grief, since I don't like adding too much tool-specific code.

Nevertheless I'm open to adding "exact highlighting". Let me play around with this idea for a bit and see if I encounter any technical problems.

**Comment by purpleP** [comment]
@mhinz Thanks, will be glad if this would be added.

**Comment by mhinz** [comment]
I played around with the idea for a bit, but all solutions seem quite flakey to me.

Nevertheless I let the issue open in case someone wants to have a try on it.

**Comment by mhinz** [comment]
I'm closing this since I'm going into maintenance mode for this plugin. I'll still fix bugs but I won't add new features on my own.
