### ISSUE TITLE
rg search doesn't work with strings beginning with hyphen

### ISSUE THREAD

**Issue by m1foley** [mhinz/vim-grepper#67]
Calling `:GrepperRg` with a string beginning with a hyphen leads to an error:

```
:GrepperRg '-foo'

  1 || Unknown flag: '-f'
  2 ||-
  3 || Usage: rg [options] -e PATTERN ... [<path> ...]
  4 ||        rg [options] <pattern> [<path> ...]
  5 ||        rg [options] --files [<path> ...]
  6 ||        rg [options] --type-list
  7 ||        rg [options] --help
  8 ||        rg [options] --version
[Quickfix List] rg --no-heading --vimgrep -i '-foo'                1,1             All
```

Nothing special is in my vimrc for that example. I get the same result when running the command without the quotes, and when using `<Plug>(GrepperOperator)` maps.

Adding  `--` to the rg command is a workaround:

```vim
let g:grepper.rg = { 'grepprg': 'rg --no-heading --vimgrep -i --' }
```

**Comment by mhinz** [comment]
Yup, that, or using it directly in the prompt `-- --foo`.

I could hardcode it, because most people probably just key in queries, but then one would lose the ability to give options in the prompt.

Some people might prefer case-sensitive searches and use:

```vim
let g:grepper.rg = { 'grepprg': 'rg --no-heading --vimgrep' }
```

Then, in the prompt, they could still use `-i query`, in case it should be needed.

Would adding this issue to the FAQ (`:h grepper-faq`) a good solution?

**Comment by m1foley** [comment]
Adding `-e`/`--regexp` seems to fix it, and it's preferable to `--` because more flags can be added.

```vim
let g:grepper.rg = { 'grepprg': 'rg --no-heading --vimgrep --regexp' }
```

It might be better if `<Plug>(GrepperOperator)` used `--fixed-strings` instead of `--regexp` for efficiency, but then logic would be needed to not escape special chars in that case.

I was going to suggest this in another issue, but I agree that `-i` shouldn't be in `g:grepper.rg` by default. I think it should be default or smart-case.

FWIW here's my vimrc:

```vim
Plug 'mhinz/vim-grepper'
set grepprg=rg\ no-heading\ --vimgrep
let g:grepper = {}
let g:grepper.tools = ['rg']
let g:grepper.prompt = 0
let g:grepper.highlight = 1
" remove ignore-case from defaults
let g:grepper.rg = { 'grepprg': 'rg --no-heading --vimgrep --regexp' }
" backslash for Grepper
vmap \ <Plug>(GrepperOperator)
nmap \ <Plug>(GrepperOperator)
" double-backslash for Grepper prompt
nmap \\ :Grepper -prompt -grepprg rg --no-heading --vimgrep --smart-case --regexp<CR>
" K searches word
nnoremap K :GrepperRg <cword><CR>
```

**Comment by mhinz** [comment]
> Adding -e/--regexp seems to fix it, and it's preferable to -- because more flags can be added.

But then the order is important, and a new user could be confused why `--foo -i` isn't working as expected.

Honestly, I think (hope) that people simply get used to using `--` instead, since it's what they would have to use in the command-line anyway. Maybe the plugin even has something educational that way...

> I was going to suggest this in another issue, but I agree that -i shouldn't be in g:grepper.rg by default. I think it should be default or smart-case.

Oh, right. That's not consistent with the other defaults. I'll remove the `-i`.

**Comment by m1foley** [comment]
Oh yeah, good call with `--regexp` being order-dependent. For prompt and command mode, I think we'll have to live with the fact that there's weird behavior with strings that begin with hyphens.

`<Plug>(GrepperOperator)` is a different story though: since the user can't add flags, I bet we can lock it down by adding `--`.

**Comment by mhinz** [comment]
Should be working for the operator now!

**Comment by mhinz** [comment]
Well, I guess all the concerns raised are either discussed or resolved by now.

Thanks for the valuable feedback!

**Comment by m1foley** [comment]
Verified that the edge case works with the operator now. Thanks!
