### ISSUE TITLE
passing -G options broke

### ISSUE THREAD

**Issue by mellery451** [mhinz/vim-grepper#73]
I've had the following mapping defined for a while now:

`nnoremap <leader>sc  :Grepper -tool ag -grepprg ag --vimgrep -G '\.(h\\|hh\\|hpp\\|H\\|HH\\|HPP\\|c\\|cc\\|cpp\\|C\\|CC\\|CPP\\|ipp\\|IPP)$' <cr>
`

..and it was working as intended until a few weeks ago. I'm not sure what might have changed, but I could use some advice on how to debug this. Thanks.

**Comment by mhinz** [comment]
You're right! Recently there was a change that made one of the two escapes unnecessary.

Basically one escape is needed because `|` has a special meaning in mappings and one _was_ needed because `|` has a special meaning in the command line (see `:h :bar`).

But the latter is only true as long as the command was defined with the `-bar` flag. (See `:h :command-bar`) That means you could do something like `:Grepper ... | wq`. But since that's very rarely the case, we removed the `-bar` flag, so `:Grepper` can never be followed by another Vim command, but now you don't have to escape the `|` anymore.

So, this should work for you:

```
nnoremap <leader>sc :Grepper -tool ag -grepprg ag --vimgrep -G '\.(h\|hh\|hpp\|c\|cc\|cpp\|ipp)$' <cr>
```

(In my quick tests the upper variants weren't needed, as long as case-sensitivity is also forced via `-s`.)

**Comment by mellery451** [comment]
perfect - removing the extra escape does the trick. Thanks!
