### ISSUE TITLE
View locking with Neovim

### ISSUE THREAD

**Issue by ViViDboarder** [mhinz/vim-grepper#8]
When I search I can see Job Control is being used, but my view still ends up locking.

It _might_ be the quickfix window though locking it when results come back. Have you seen this happen when you have large results sets? Like 10k?

**Comment by mhinz** [comment]
Yup, the problem is that the search itself is asynchonous, but populating the quicklix list afterwards is not. If you use a slower grep tool, e.g. `grep`, you'll notice that you can navigate as long as the search is running.

Unfortunately there's nothing one can do about it with what Neovim provides at the moment. I hope it's just a theoretical issue and you usually don't search for something that returns 10k hits. :)

**Comment by ViViDboarder** [comment]
Hah, yea. I just installed it so decided I'd test by doing a large search and see how it handled. Ag is just too fast so it seemed to immediately lock. Oh well!

Unrelated: Is there a way to immediately execute a search similar to how `:grep foo` will execute right away?

**Comment by mhinz** [comment]
Yup, you can do that with the `-query` flag. See `:h :Grepper`.

Example:

```vim
command! -nargs=* -complete=file GG Grepper! -tool git -query <args>
```

Afterwards you can it like this: `:GG foo` or `:GG 'foo bar' *.txt` etc.
