### ISSUE TITLE
In the Wiki page on the operator, use `vmap` to bind `gs` to `Grepper` in visual mode

### ISSUE THREAD

**Issue by cttttt** [mhinz/vim-grepper#81]
Was just running through [the wiki page on operators](https://github.com/mhinz/vim-grepper/wiki/using-the-operator) and noticed that the following `vimrc` snippet was included:

```
nmap gs  <plug>(GrepperOperator)
nmap gs  <plug>(GrepperOperator)
```

Instead of using `nmap` twice in a row, you probably intended to use `vmap` on the second line.

Kinda wish I could open a pull request against the Wiki, but I guess an issue will have to do.

Lemme know if this was unclear, and btw; this is an awesome plugin!

**Comment by mhinz** [comment]
Oops. Thanks for noticing!

> this is an awesome plugin!

Thanks again!

---

By the way, most people really want `xmap` instead of `vmap`, because the former maps for visual mode and the latter for visual mode _and_ select mode. Select mode is usually never used and it makes no difference in practice, but using `xmap` feels more precise.
