### ISSUE TITLE
Export s:defaults globally

### ISSUE THREAD

**Issue by sergei-dyshel** [mhinz/vim-grepper#84]
I mean, make it a global variable (e.g. `g:grepper_defaults`) so that one could customize tools incrementally. For example:
```vim
let g:grepper.rg = g:grepper_defaults.rg
let g:grepper.rg.grepprg .= ' --smart-case'
```

**Comment by mhinz** [comment]
I assume you want to put that in your vimrc. The problem is that the vimrc is sourced first, so `g:grepper_defaults.rg` wouldn't exist yet.

You can work around that using an autoload variable, but that's rather ugly. Hmm.

In case you didn't know, after using `:Grepper` for the first time, the `g:grepper` from your vimrc (if it was set) gets enriched by all the default values.

Try this after using `:Grepper`:

```vim
:for [k,v] in items(g:grepper) | echomsg k .':' string(v) | endfor
```

I guess autoloading is our best option, though. So, I could expose the function that enriches `g:grepper` with the defaults. Then it could look like...

```
let g:grepper = {}
let g:grepper.git = { 'grepprg': '..... }
let g:grepper = grepper#merge_with_defaults(g:grepper)
let g:grepper.rg.grepprg .= ' --smart-case'
```

What do you think?

**Comment by sergei-dyshel** [comment]
Sounds good. You just will have to mention in README that this kind of configuration (using autoload) must happen after plugin manager's `end` function, since only there plugin directories are added to `runtimepath`.

Another option for user would be to use `after/plugin` feature but I like it less since it won't let the user store entire configuratio in single `.vimrc` file.

**Comment by sergei-dyshel** [comment]
Slightly off-topic, some people may interpret `-query` option as it must be followed by the pattern only, but actually one can add any grep tool arguments to it. IMHO this is very important feature and is worth to be mentioned explicitly.

**Comment by mhinz** [comment]
Wait, actually, this should work already:

```vim
runtime autoload/grepper.vim
let g:grepper.rg.grepprg .= ' --smart-case'
```

**Comment by sergei-dyshel** [comment]
Thanks!

**Comment by mhinz** [comment]
The above commit also adds your exact use case to `:h grepper-tools`.

Thanks for bringing this up! :-)
