### ISSUE TITLE
Live result while searching

### ISSUE THREAD

**Issue by neilpeter08** [mhinz/vim-grepper#94]
Is it possible to see the partial found searches?

**Comment by mhinz** [comment]
I could change it to do so, but it would have quite some consequences. E.g. `:Grepper -open` would open the qf window right away (instead of waiting until finished), `:Grepper -jump` would have to jump when the first match was found (instead of waiting until finished), and so on.

But I can make the actual change without breaking `:Grepper`'s current interface, if you simply run `:copen` yourself afterwards.

**Comment by neilpeter08** [comment]
Manually opening the qf window is fine for me. Thanks for considering this as a feature mhinz!

**Comment by mhinz** [comment]
Okay. Please use `git pull && git checkout immediate-output` and see if it's working as expected. (That is, `:Grepper` followed by `:copen`.)

**Comment by neilpeter08** [comment]
Working as expected! Thanks @mhinz :1st_place_medal:

**Comment by mhinz** [comment]
Awesome! It's in master now.
